name: Build and Push Docker Image

on:
  push:
    branches:
      - dev
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to zypl2registry (Docker images registry)
      uses: docker/login-action@v2
      with:
        registry: zypl2registry.azurecr.io
        username: ${{secrets.REGISTRY_USERNAME2}}
        password: ${{secrets.REGISTRY_PASSWORD2}}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: zypl2registry.azurecr.io/${{vars.IMAGE_NAME}}:dev
        
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ vars.HOST }}
        username: ${{ secrets.DEFAULT_LOGIN }}
        key: ${{ secrets.DEFAULT_PRIVATE_KEY }}
        port: 22
        script: |
          cd /home/zypl4admin/back-dev/
          docker-compose down
          docker login zypl2registry.azurecr.io --username ${{ secrets.REGISTRY_USERNAME2 }} --password ${{ secrets.REGISTRY_PASSWORD2 }}
          docker rmi zypl2registry.azurecr.io/${{vars.IMAGE_NAME}}:dev
          docker pull
          docker-compose up -d